### ISSUE TITLE
be abble to add units in the editor

### ISSUE THREAD

**Issue by RenanJooj** [Anuken/Mindustry-Suggestions#1854] opened 2021-01-22 13:23 UTC
like a block be abble to add units itself in the editor for maps

**Comment by joshuaptfan** [comment] 2021-01-22 13:24
Duplicate of #1672

@RenanJooj please close this suggestion.

**Comment by DeltaNedas** [comment] 2021-01-22 13:27
3. already possible see deltanedas/unit-factory

**Comment by TheRealIvyX** [comment] 2021-01-22 13:29
how is this a duplicate of 1672. im pretty sure that the person who suggested this wants to be able to place units in the editor like how you can place blocks in the editor or something

**Comment by joshuaptfan** [comment] 2021-01-22 13:30
I interpreted it as "a block placeable in the editor that can spawn units".

**Comment by TheNightglow** [comment] 2021-01-22 14:04
> 
> 
> I interpreted it as "a block placeable in the map editor that can spawn units".

I think what is meant here is to have a faction start with a bot, not with a bot source

for instance, allow the player to start with exactly 1 Quasar for a puzzle map where the player is supposed to control a ground unit / a pvp mech map

or have the enemy start with an Oct locked in place with logic as a shield etc

I d also like a way to let a faction start with bots while not giving them bot sources

**Comment by itcannotbe** [comment] 2021-01-22 14:54
@joshuaptfan Wrong issue. It's #1718

**Comment by RenanJooj** [comment] 2021-01-23 00:03
sorry for it beeing a duplicate i apolagise

**Closed** 2021-01-23 00:09 UTC
Labels: feature request
