### ISSUE TITLE
Make it so that we can skip the template

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry-Suggestions#2079] opened 2021-03-02 04:28 UTC
As you can see, I have skipped the template and managed to create an issue without any tags or templates involved. Make this possible

**Comment by GreyMario** [comment] 2021-03-02 04:36
Duplicate of #2078.

**Comment by Bohaska** [comment] 2021-03-02 06:46
Fixed, now it isn't a duplicate

**Comment by sample-text-here** [comment] 2021-03-02 07:07
> Make it so that we can skip the template

> As you can see, I have skipped the template 

feic

**Comment by Bohaska** [comment] 2021-03-02 10:45
I'm hungry

**Closed** 2021-03-02 10:45 UTC
