### ISSUE TITLE
I figured out how to re-open it

### ISSUE THREAD

**Issue by Bobbystevenson** [Anuken/Mindustry-Suggestions#2050] opened 2021-02-26 11:19 UTC
Im proposing new smart liquids to make the progression system less bland, either that or more uses for liquids.
Half the liquids in this game serve no unique purpose other than to make a specific item(s).

The basic concept is that combining certian items with slag would give it a more practical purpose. Eg mixing slag with Silicon plast and phase would make a liquid to speed up factories. Mixing slag with Large amounts of silicon, copper, lead and plastinium would provide a liquid that could boost support buildings.

It would make defenses more intricate, at this point all you have to do is make a line of fuses and parallaxes. I suppose it could also make more tsunami [insert tower here] combos.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

Also Natalie im aware tsunamis exist.

**Comment by NajimiOsana** [comment] 2021-02-26 11:24
You should've kept it closed.

**Comment by GreyMario** [comment] 2021-02-26 11:26
Duplicate of #2049

**Comment by itcannotbe** [comment] 2021-02-26 11:31
@Bobbystevenson Revisit your closed suggestion and you'll see a reopen button somewhere.

**Comment by joshuaptfan** [comment] 2021-02-26 13:14
Reopen button is under the comment box, next to the "Comment" button.

**Comment by marky0470** [comment] 2021-02-26 13:57
But liquids are viable in defense. Water has high knockback, cryofluid freezes and slows enemies, and synergizes with blast, oil slows enemies so they can be lit on fire easily and slag has dot. All of these are definitely incentivizing the use of tsunamis in defenses

**Comment by Thankyou69** [comment] 2021-02-26 19:08
close this please, i suggest using vanilla++ or diamonds mod to add more liquids

**Comment by WinterCrystal** [comment] 2021-02-27 00:36
> It would make defenses more intricate, at this point all you have to do is make a line of fuses and parallaxes.

I mean, you can do that, if you want to get your defenses get destroyed by air crash damage, that is.

**Comment by SheepCommander** [comment] 2021-02-27 00:40
*close*

**Comment by Newguy-ish** [comment] 2021-02-27 13:03
Dude, at this point just make your own. Modding in simple things like this is incredibly easy.

**Comment by liuxilu** [comment] 2021-02-28 04:01
#2049 is reopened, so close this.

**Closed** 2021-02-28 17:39 UTC
Labels: feature request
