### ISSUE TITLE
Liquid Neoplasm Tiles

### ISSUE THREAD

**Issue by Novanox4** [Anuken/Mindustry-Suggestions#4957] opened 2024-04-09 15:42 UTC
### Describe the content or mechanics you are proposing.

A tile that is liquid neoplasm

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Since V8 will be **flesh**ing neoplasm out, liquid neoplasm could have some interesting mechanics related to that. Maybe neoplastic units could use bodies of neoplasm to heal quickly when they are low, nearby water pipes could get infested so players need to navigate waterworks around the pools, and it is flammable so it could catch on fire like a less explosive oil, but on Erekir. Pools could also act as a buff to neoplastic buildings, making them regenerate and extend faster, as well as other stat improvements.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [x] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by jehosula** [comment] 2024-04-09 16:19
neoplasm is not dormant tho and adding it as a pumpable liquid would make things weird

**Comment by Novanox4** [comment] 2024-04-09 16:22
> neoplasm is not dormant tho and adding it as **a pumpable** liquid would make things weird

Wouldn't be pumpable tho

**Comment by Novanox4** [comment] 2024-04-09 18:09
> > **Wouldn't be pumpable tho,**

**Comment by jehosula** [comment] 2024-04-09 22:33
> > > **Wouldn't be pumpable tho,**

yeah??
did you not realize that liquid tiles are infinite so if there is a neoplasm tile it would be infinite and that's just too weird cause neoplasm isn't dormant

**Comment by Novanox4** [comment] 2024-04-09 22:43
> yeah??
> did you not realize that liquid tiles are infinite so if there is a neoplasm tile it would be infinite and that's just too weird cause neoplasm isn't dormant

Infinite as in???

**Comment by jehosula** [comment] 2024-04-09 22:58
> Infinite as in???

there i infinite liquid there so it does not run out

**Comment by Novanox4** [comment] 2024-04-09 22:59
> there i infinite liquid there so it does not run out

And whay do you use to get that liquid out, huh?

**Comment by jehosula** [comment] 2024-04-09 23:02
> And whay do you use to get that liquid into pipes, huh?

pumps, why is that even relevant

**Comment by Novanox4** [comment] 2024-04-09 23:04
> pumps, why is that even relevant
>>>it would be **UN***PUMPABLE* tho

**Comment by jehosula** [comment] 2024-04-09 23:05
> > pumps, why is that even relevant
> > > > it would be **UN**_PUMPABLE_ tho

yeah?!?!
wouldn't the neoplasm just.. ya know crawl out?!?!

**Comment by jehosula** [comment] 2024-04-09 23:06
> yeah?!?! wouldn't the neoplasm just.. ya know crawl out?!?!

that's the biggest weird part about this idea

**Comment by Novanox4** [comment] 2024-04-09 23:07
> yeah?!?!
> wouldn't the neoplasm just.. ya know crawl out?!?!

How?

**Comment by Novanox4** [comment] 2024-04-09 23:09
> idk just neoplasm doing neoplasm things it's gonna be in V8 my guy neoplasm would figure this out

How do you know?

**Comment by jehosula** [comment] 2024-04-09 23:12
> How do you know?

v8 teasers show what the neoplasm can do, it would be a no brainer to assume it can also just crawl out of this

**Comment by Novanox4** [comment] 2024-04-09 23:14
>v8 teasers show what the neoplasm can do, it would be a no brainer to assume it can also just crawl out of this 

Neoplasm itself can only multiply it when near **water**, wich can be only found as a liquid inside pipes on Erekir. You are confusing neoplasm with *neoplastic units*. Neoplasm is the blood, the units do the crawling.

**Comment by jehosula** [comment] 2024-04-09 23:17
> Neoplasm itself can only multiply it when near **water**, wich can be only found as a liquid inside pipes on Erekir. You are confusing neoplasm with _neoplastic units_. Neoplasm is the blood, the units do the crawling.

the neoplasm liquid can spawn units and well there is infinite neoplasm in a neoplasm tile so the neoplasm there can just turn into units and crawl out
also neoplasm mainly multiplies with vents in v8 too did you not see the "leaks"

**Comment by Novanox4** [comment] 2024-04-09 23:20
> the neoplasm liquid can spawn units and well there is infinite neoplasm in a neoplasm tile so the neoplasm there can just turn into units and crawl out
> also neoplasm mainly multiplies with vents in v8 too did you not see the "leaks"
The neoplasm actually needs resources such as berryilium, tungsten or thorium fed into a special neoplastic building to make units. The veins also need to have a **neoplastic heart**, wich can only spawn on top of vents.

**Comment by jehosula** [comment] 2024-04-09 23:23
> The neoplasm actually needs resources such as berryilium, tungsten or thorium fed into a special neoplastic building to make units. The veins also need to have a **neoplastic heart**, wich can only spawn on top of _vents_.

yeah i did see the "leaks" and well i am sure some smaller units can be made without Resorces like idk blobs that can start the outbreak and the neoplastic heart is kind of the part i left out still needs vents

**Comment by Novanox4** [comment] 2024-04-09 23:27
> yeah i did see the "leaks" and well i am sure some smaller units can be made without Resorces like idk blobs that can start the outbreak and the neoplastic heart is kind of the part i left out still needs vents

To create a unit it needs a building to make it or a drop zone. To create a building it would need veins. To create veins it would need a heart. To create a heart it would need a vent. The pools of neoplasm would most likely not infect a vent unless adjacent to one or maybe not infect them at all.

**Comment by jehosula** [comment] 2024-04-09 23:29
> To create a unit it needs a building to make it or a drop zone. To create a building it would need veins. To create veins it would need a heart. To create a heart it would need a vent. The pools of neoplasm would most likely not infect a vent unless adjacent to one or maybe not infect them at all.

where will it start then and also it will just continuously pump out units with infinite neoplasm

**Comment by Novanox4** [comment] 2024-04-09 23:32
> where will it start then 
>>and also it will just continuously pump out units with infinite neoplasm

1: It may start with a neoplasm heart being directly placed upon a vent in the editor or through a unit spawned by natural waves burrowing inside

2: It already pumps out a ton of units.

**Comment by jehosula** [comment] 2024-04-09 23:36
> 1: It may start with a neoplasm heart being directly placed upon a vent in the editor or through a unit spawned by natural waves burrowing inside
> 
> 2: It already pumps out a ton of units indefinitely.

IT CAN ALSO BE A NEOPLASIA REACTOR EXPLODING THEN THE SPILLED NEOPLASM MAKING A UNIT THAT GOES TO A VENT, HOW DID YOU NOT KNOW THAT Bruh
also i mean like one or 2 units/s for a single tile

**Comment by Novanox4** [comment] 2024-04-09 23:39
> IT CAN ALSO BE A NEOPLASIA REACTOR EXPLODING THEN THE SPILLED NEOPLASM MAKING A UNIT THAT GOES TO A VENT, HOW DID YOU NOT KNOW THAT Bruh
> also i mean like one or 2 units/s for a single tile

Spilled neoplasm cannot make a unit. Neoplasm is like blood. A mouse won't emerge from a pile of blood. It needs a special neoplastic building to produce it.

**Comment by jehosula** [comment] 2024-04-09 23:41
> Spilled neoplasm cannot make a unit. Neoplasm is like blood. A mouse won't emerge from a pile of blood. It needs a special neoplastic building to produce it.

then how would you start a neoplasm outbreak yourself?

**Comment by Novanox4** [comment] 2024-04-09 23:43
> then how would you start a neoplasm outbreak yourself?

You wouldn't need to. If you want to see and test how it works, then maybe use a mod to spawn a neoplastic unit and infest a vent, but I doubt Anuke would make it possible to start an outbreak in campaign, especially after capturing a sector

**Comment by jehosula** [comment] 2024-04-09 23:46
> You wouldn't need to. If you want to see and test how it works, then maybe use a mod to spawn a neoplastic unit and infest a vent, but I doubt Anuke would make it possible to start an outbreak in campaign, especially after capturing a sector

it's basically confirmed that you can start a neoplasm outbreak by exploding a neoplasia reactor or mismanaging the spill

**Comment by Novanox4** [comment] 2024-04-09 23:51
> it's basically confirmed that you can start a neoplasm outbreak by exploding a neoplasia reactor or mismanaging the spill

Still, this will only make a heart, wich will in turn create unit factories. A puddle of neoplasm cannot move, only multiply via water, so a neoplasm terrain block won't start making units.

**Comment by jehosula** [comment] 2024-04-09 23:56
> Still, this will only make a heart, wich will in turn create unit factories. A puddle of neoplasm cannot move, only multiply via water, so a neoplasm terrain block won't start making units unless right next to a vent.

"Still, this will only make a heart, wich will in turn create unit factories" yes
"A puddle of neoplasm cannot move, only multiply via water, so a neoplasm terrain block won't start making units unless right next to a vent" well it can make blobs and i am pretty sure neoplasm will seek out vents instead of just being hopeless because the vent is too far
"wich is a thing I doubt Anuke would turn into a sector, as it would make it uncapturable." it would also make maps unwinnable so it shouldn't be added
unless it's just like 1k neoplasm stored like it's a block then no this suggestion is trash

**Comment by jehosula** [comment] 2024-04-09 23:57
them it should just be a block for mappers to add instead of something like this and unnecicarily breaking concictency

**Comment by Novanox4** [comment] 2024-04-10 00:01
> "A puddle of neoplasm cannot move, only multiply via water, so a neoplasm terrain block won't start making units unless right next to a vent" well it can make blobs and i am pretty sure neoplasm will seek out vents instead of just being hopeless because the vent is too far

Your source? Was it revealed to you in a dream?

> "wich is a thing I doubt Anuke would turn into a sector, as it would make it uncapturable." it would also make maps unwinnable so it shouldn't be added

Custom maps are already unwinnable unless it is an attack/pvp map, wich ends when destroying the enemy team, or if mods are used to put an end wave, which would end the map after the wave is cleared, and neoplasm hearts don't count towards waves

> unless it's just like 1k neoplasm stored like it's a block then no this suggestion is trash

Please elaborate.

**Comment by jehosula** [comment] 2024-04-10 00:10
> Your source? Was it revealed to you in a dream?

no it was those exact leaks you must have saw

> Custom maps are already unwinnable unless it is an attack/pvp map, wich ends when destroying the enemy team, or if mods are used to put an end wave, which would end the map after the wave is cleared, and neoplasm hearts don't count towards waves

well wave limits are already in the campaign and are used pretty often when making maps via mods so they should be accounted for

> Please elaborate.

i mean something that stores neoplasm to spill at any time to start a neoplasm outbread

**Comment by jehosula** [comment] 2024-04-10 00:10
also about the second one for pvp it would turn into last man standing
and for attack it would make it unwinnable there

**Comment by Novanox4** [comment] 2024-04-10 00:15
>no it was those exact leaks you must have saw

Show me.

> well wave limits are already in the campaign and are used pretty often when making maps via mods so they should be accounted for

The difference between campaign and custom maps are that while in custom maps, when you reach the end wave the game simply ends, in campaign you are - still playing on the map.

> i mean something that stores neoplasm to spill at any time to start a neoplasm outbreak

Still, it does not have anything to do with the liquid neoplasm terrain.

**Comment by jehosula** [comment] 2024-04-10 00:21
> Show me.

search it up on youtube, before acting like you know all of v8
 
> The difference between campaign and custom maps are that while in custom maps, when you reach the end wave the game simply ends, in campaign you are - still playing on the map.

that's because you already captured the sector and also the wave after the last never shows up with enemies still in the map

> Still, it does not have anything to do with the liquid neoplasm terrain.

it would be a proper starter for neoplasm outbreaks and it's not supposed to be similar
or maybe just a neoplasm INFESTED tile for what you want, a pool of neoplasm would just be silly

**Comment by Novanox4** [comment] 2024-04-10 00:34
> search it up on youtube, before acting like you know all of v8
  
![Screenshot_20240410-033138_Discord.jpg](https://github.com/Anuken/Mindustry-Suggestions/assets/154760485/e84c09f3-fce7-4d89-a328-c8b3bb0d9c37)

**Comment by jehosula** [comment] 2024-04-10 00:37
> ![Screenshot_20240410-033138_Discord.jpg](https://private-user-images.githubusercontent.com/154760485/321035981-e84c09f3-fce7-4d89-a328-c8b3bb0d9c37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDk2NTcsIm5iZiI6MTcxMjcwOTM1NywicGF0aCI6Ii8xNTQ3NjA0ODUvMzIxMDM1OTgxLWU4NGMwOWYzLWZjZTctNGQ4OS1hMzI4LWM4YjNiYjBkOWMzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwMDM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTgxZDA1NWU3MTI4MmVhYjFkMjA5YmFkYWYyN2I0NzFhNGNhN2QyNTNhODQxMGViZDIyNTVmNzBiM2Q5NmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7qtOv2QyI9jSF5Cw2w7mS3_2cKzEY2Wy2oJRbDJS74s)
> 
> Stop acting like YOU know all of V8

YEAH?!?!?! I SAID THE **_UNITS_** THAT SPAWN FROM THE LEAKS

**Comment by Novanox4** [comment] 2024-04-10 00:41
> YEAH?!?!?! I SAID THE **_UNITS_** THAT SPAWN FROM THE LEAKS

How do you know units spawn from leaks lol

**Comment by jehosula** [comment] 2024-04-10 00:48
> How do you know units spawn from leaks lol

re read the message you refrenced

**Comment by Novanox4** [comment] 2024-04-10 00:50
> re read the message you refrenced

If you are talking about that "they" Anuke used, it most likely referenced another unit that creates units or a unit factory.

**Comment by Novanox4** [comment] 2024-04-10 00:52
Also, this does not prove that liquid neoplasm terrain is stupid.

**Comment by jehosula** [comment] 2024-04-10 00:55
> If you are talking about that "they" Anuke used, it most likely referenced another unit that creates units or a unit factory.

there is no context indicating that and simple grammar would indicate that he meant the liquid spill

**Comment by jehosula** [comment] 2024-04-10 00:56
> Also, this does not prove that liquid neoplasm terrain is stupid.

in the way you suggested then it does because it would make no sense for it to not just crawl out and start an invasion

**Comment by jehosula** [comment] 2024-04-10 00:57
even the context indicates that the spill does spawn units

**Comment by Novanox4** [comment] 2024-04-10 00:58
> in the way you suggested then it does because it would make no sense for it to not just crawl out and start an invasion

Wouldn't they just drown?

**Comment by jehosula** [comment] 2024-04-10 01:01
> Wouldn't they just drown?

umm are you saying the neoplasm will drown in itself?!?
what does it even breathe?

**Comment by Novanox4** [comment] 2024-04-10 01:03
Whatever. Let's just agree to disagree and end this argument. This feature will prolly not even get added so we should just stop fighting over such a stupid reason.

**Comment by jehosula** [comment] 2024-04-10 01:04
> Whatever. Let's just agree to disagree and end this argument. This feature will prolly not even get added so we should just stop fighting over such a stupid reason.

yeah i was waiting for you to stop for such a bad feature so no more comments, close this and we both move on

**Closed** 2024-04-10 01:05 UTC
Labels: feature request
