### ISSUE TITLE
Upgrade system

### ISSUE THREAD

**Issue by RetroGaming2077** [Anuken/Mindustry-Suggestions#241] opened 2020-06-14 03:24 UTC
putting an improvement system in turrets, units and mechs would make the resources more useful.

**Comment by RogueRedHawk** [comment] 2020-06-14 04:22
Upgrade systems for drones are currently being worked on for the 6.0 update.

**Comment by RogueRedHawk** [comment] 2020-06-14 04:28
https://cdn.discordapp.com/attachments/513178557653188609/721548117044101171/2020-06-13_22-12-57.gif

**Comment by itcannotbe** [comment] 2020-06-14 07:55
Sort of duplicate of #157 but in general.

**Closed** 2020-06-14 13:50 UTC
Labels: feature request
