### ISSUE TITLE
Unit Visibility Toggle and Hotkey

### ISSUE THREAD

**Issue by marky0470** [Anuken/Mindustry-Suggestions#1762] opened 2021-01-10 06:24 UTC
**Describe the content or mechanics you are proposing.**
An option to make units invisible via an option in settings or more preferably, toggling a hotkey. 

There could also be an extra option which makes it so that if the player currently has a block selected, the unit visibility is decreased. Though it would be preferable if the units did not completely disappear, Another suggestion on how to retain some visibility on the units is to render only their outlines or shadows

**Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.**
Units have become increasingly viable in supplementing or even replacing most traditional defenses, but of course it becomes increasingly difficult to build when units are in the way. And even without that scenario in place, the fact that V6 has brought us units with larger sizes and even legs to further impede visibility makes this a bigger problem.

I am aware that we could simple move those units out of the way or have them all in one spot, but this is a hassle, especially with slower moving units, and there are many cases where units are positioned somewhere for a purpose, be it a shield or extra firepower. This should be a solution where relocations and limited positioning of units are avoided.

**Before making this issue, place an `X` in the boxes below to confirm that you have acknowledged them.** *Failure to do so may result in your request being closed automatically.*

1. - [X] I have done a quick search in the list of suggestions to make sure this has not been suggested yet.
2. - [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
3. - [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
4. - [X] I have read `README.md` to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by joshuaptfan** [comment] 2021-01-10 06:35
Duplicate of #1376 #873 #108

**Comment by marky0470** [comment] 2021-01-10 06:40
I see, I'm sorry, I guess I haven't done enough searching, I saw #1596 but thought that it was different in it making units all invisible. I should've expected that many others would have suggested this by now. However I think that my idea of retaining some visibility on units by instead showing their outlines or shadows is something different. Thank you for pointing this out @joshuaptfan.

**Comment by joshuaptfan** [comment] 2021-01-10 07:10
The automatic unit transparency while placing blocks is new, and might serve mobile players better, being that toggle hotkeys are not available to them.

**Closed** 2021-01-10 11:15 UTC
Labels: feature request
