### ISSUE TITLE
Allow logic "itemDrop" to @air

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry-Suggestions#2878] opened 2021-08-21 11:45 UTC
### Describe the content or mechanics you are proposing.

When the "Core Incinerates Overflow" opition is disabled: 
If the copper is full but lead isn't, mono will drop the its copper "to air" and go to mine lead. But the unit which controlled by logic cannot do this like mono.
So I think it's necessary to make command "itemDrop" can let unit drop item to @air.

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

Unit can drop item to @air by "itemDrop" command.

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by Yell245** [comment] 2021-08-21 16:15
To people who say "griefing". Just make a server rule that disallows units from doing this

**Comment by Kyllingene** [comment] 2021-08-21 17:38
Duplicate of #2749.

**Comment by Hexrotor** [comment] 2021-08-21 23:41
> To people who say "griefing". Just make a server rule that disallows units from doing this

Or: Units can do this only when the core is full.

**Closed** 2021-08-23 06:56 UTC
Labels: feature request

**Comment by itcannotbe** [comment] 2021-08-23 07:06
> > To people who say "griefing". Just make a server rule that disallows units from doing this
> 
> Or: Units can do this only when the core is full.

Or drop them into the nearest incinerator.

###### Oh wait. That's implemented you say?
###### ~Then why this suggestion even exists?~

**Comment by Hexrotor** [comment] 2021-08-23 07:37
> Or drop them into the nearest incinerator.
> 
> ###### Oh wait. That's implemented you say?
> ###### ~Then why does this suggestion even exists?~

im sorry bro
