### ISSUE TITLE
Last erekir sector is just BS

### ISSUE THREAD

**Issue by TheAirBlow** [Anuken/Mindustry-Suggestions#4085] opened 2022-11-05 16:58 UTC
### Describe what you would like changed, and why.

I destroyed all cores except one, and after that I heard wave sounds... I placed a Scathe and saw this;
![image](https://user-images.githubusercontent.com/68467762/200131989-a046d534-1945-4ff1-b5c6-2d0f10a912f8.png)
What the actual fuck is this? How am I even supposed to defend against that?
Maybe they started to just multiply and camp this place because their place is lit. 
But still, getting like ~8 of them per wave is just something TOO hard to defend against.

<details>
<summary>Scathe attack attempt</summary>
<br>
<img src="https://user-images.githubusercontent.com/68467762/200132483-a44908ec-cf0a-4cbe-8b60-aab4b4d2091d.png"/>
<img src="https://user-images.githubusercontent.com/68467762/200132498-d365107d-2a86-4b95-9409-a584cdde8055.png"/>
<img src="https://user-images.githubusercontent.com/68467762/200132503-be31395d-8676-4fd7-8ee2-1b5dbe7fc50e.png"/>
<img src="https://user-images.githubusercontent.com/68467762/200132518-c41d9ec1-7424-4afb-96e6-c30093f3cc06.png"/>
</details>

<details>
<summary>Core death and defences die</summary>
<br>
<img src="https://user-images.githubusercontent.com/68467762/200132574-97069e27-6f64-4e87-b85d-e8363fec883c.png"/>
<img src="https://user-images.githubusercontent.com/68467762/200132658-a66310d0-ad54-4cee-8fda-0421c5b07963.png"/>
</details>

<details>
<summary>Another core death and range of these fuckers</summary>
<br>
<img src="https://user-images.githubusercontent.com/68467762/200132727-d763bcd7-c7e7-4e0e-9d58-c2a1dc35eb5a.png"/>
<img src="https://user-images.githubusercontent.com/68467762/200132765-2a947139-b378-4581-9031-0fe62a1b80b0.png"/>
</details>

### Describe the changes you want to propose. Include possible alternatives.

Remove the waves completely or make them less OP

**Comment by SecondNewtonLaw** [comment] 2022-11-05 17:14
can vouch on this, the way this was implemented it's absurd, it's too hard to get through the sector, more when you don't get an indication of it at ANY moment during the game, no counter to see when they come, or the fact that they obtain absurd amounts of units, disipite there only being ONE available core.

**Comment by SecondNewtonLaw** [comment] 2022-11-05 17:16
although this is likely EXPLICITLY programmed, this is just too unfair, even for a sector with the highest difficulty, I know it's 'Bleeding Edge' and not Stable, but this is too exaggerated of a balancing issue.

**Comment by Bottinator22** [comment] 2022-11-05 19:25
> although this is likely EXPLICITLY programmed, this is just too unfair, even for a sector with the highest difficulty, I know it's 'Bleeding Edge' and not Stable, but this is too exaggerated of a balancing issue to even be on a BE build in my opinion.

"but this is too exaggerated of a balancing issue to even be on a BE build"
do you have any idea what BE even is?

**Comment by TheAirBlow** [comment] 2022-11-05 20:01
> > although this is likely EXPLICITLY programmed, this is just too unfair, even for a sector with the highest difficulty, I know it's 'Bleeding Edge' and not Stable, but this is too exaggerated of a balancing issue to even be on a BE build in my opinion.
> 
> "but this is too exaggerated of a balancing issue to even be on a BE build" do you have any idea what BE even is?

I don't get how is it possible to make these "waves" to have 10-20 units with extremely long reach and health.

**Comment by SecondNewtonLaw** [comment] 2022-11-05 22:12
> > although this is likely EXPLICITLY programmed, this is just too unfair, even for a sector with the highest difficulty, I know it's 'Bleeding Edge' and not Stable, but this is too exaggerated of a balancing issue to even be on a BE build in my opinion.
> 
> "but this is too exaggerated of a balancing issue to even be on a BE build"
> do you have any idea what BE even is?

Yes, I know, I literally stated it "Bleeding Edge", it's supposed to not be a stable build, and to be to test features before release, that's the point, the sector is not yet balance because it's not stable yet, also, your comment came as something rude :p, you should not get that offended over a comment.

**Comment by Sector171** [comment] 2022-11-06 04:35
It was challenging and fun to defeat this sector.
It is fine to suffer in the last sector and see this "surprise" just the moment when you think it over and you win.
Replay the sector, but this time be sure you have a fast production of quells and disrupts, in addition to have decent resources production to make tough AA turrets around your cores, not necessary to take care of the defense alone but just to support your air units.
Come on , it is the last sector, should be hard and has surprises. Anyway this big group of units are not ok and should the ai be changed a bit but keeping the hard feature.

**Comment by Anuken** [comment] 2022-11-06 07:29
The idea was to provide an extra challenge at the end so players aren't faced with a boring, steadily decreasing difficulty curve... and for what it's worth, I *did* test this whole map with another person or two, waves included. It wasn't difficult to beat these waves... but then again, we faced each one head-on, and were aware of their existence. I didn't consider the fact that they could pile up this much.

Do you have a save with the enemies piled up like that? It shouldn't happen normally.

**Comment by TheAirBlow** [comment] 2022-11-06 11:42
> It was challenging and fun to defeat this sector. It is fine to suffer in the last sector and see this "surprise" just the moment when you think it over and you win. Replay the sector, but this time be sure you have a fast production of quells and disrupts, in addition to have decent resources production to make tough AA turrets around your cores, not necessary to take care of the defense alone but just to support your air units. Come on , it is the last sector, should be hard and has surprises. Anyway this big group of units are not ok and should the ai be changed a bit but keeping the hard feature.

Well, I do agree, the main problem it being TOO hard to defend againsts. Removing it entirely is just dumb if I think about it a little bit more.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 11:45
maybe what should be done is to just fix the way enemies behave during that wave phase, I believe what they intended was so they came HEAD ON towards the player, but they behaved like units wouldn't in that phase, that's what I believe.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 14:37
Ok so here is my, save file of this issue, I had to reproduce it, since I did not save my zip file of my previous runs with the stuff that happened. 

This is what happens basically.
![image](https://user-images.githubusercontent.com/107165614/200176941-1e34fc90-4f07-4f3f-90ba-1dd94205bd9b.png)

and here is the save that has that happening, sadly, I forgot to do it BEFORE it happened, I could try and reproduce it... again.
[save.zip](https://github.com/Anuken/Mindustry-Suggestions/files/9946072/save.zip)

**Comment by IVV-NCX** [comment] 2022-11-06 18:07
Time warp causes this. 

This is because increasing speed has a weird function where it also breaks the way enemies work, resulting in massive loads of enemies.

Heres the "fix": Don't use more than 4x speed, it shouldn't happen. For instance, the 256x speed or whatever, causes your base to become near-invincible.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 18:13
> Time warp causes this.
> 
> This is because increasing speed has a weird function where it also breaks the way enemies work, resulting in massive loads of enemies.
> 
> Heres the "fix": Don't use more than 4x speed, it shouldn't happen. For instance, the 256x speed or whatever, causes your base to become near-invincible.

yeah, I know that, it causes things like Bullets to not hit targets and units go random places, I have experienced it before, but the problem is that I don't remember speeding up in the playthrough I sent, I could certainly retry doing this, but without the time mod, although I can say that enemies immediately came after killing another enemy that was nearby (only one left in front), so I thought that may have been the case, in any case, thx for the response, I'll get to trying that later.

**Comment by itcannotbe** [comment] 2022-11-06 18:29
Also when complaining about something, also known as making a bug report, you should probably mention the mods you are using.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 18:30
> Also when complaining about something, also known as making a bug report, you should probably mention the mods you are using.

I did?

**Comment by itcannotbe** [comment] 2022-11-06 18:32
> ### Describe what you would like changed, and why.
> 
> I destroyed all cores except one, and after that I heard wave sounds... I placed a Scathe and saw this; ![image](https://user-images.githubusercontent.com/68467762/200131989-a046d534-1945-4ff1-b5c6-2d0f10a912f8.png) What the actual fuck is this? How am I even supposed to defend against that? Maybe they started to just multiply and camp this place because their place is lit. But still, getting like ~8 of them per wave is just something TOO hard to defend against.
> Scathe attack attempt
> Core death and defences die
> Another core death and range of these fuckers
> ### Describe the changes you want to propose. Include possible alternatives.
> 
> Remove the waves completely or make them less OP

You didn't.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 18:32
man I'm not the Original Poster.

**Comment by itcannotbe** [comment] 2022-11-06 18:33
Welp, then the message is for the OP, you get a free pass.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 18:34
> Welp, then the message is for the OP, you get a free pass.

Then why even start this? You could have avoided this all together if you had just read the messages before jumping into attack mode.

**Comment by SecondNewtonLaw** [comment] 2022-11-06 18:37
> Time warp causes this.
> 
> This is because increasing speed has a weird function where it also breaks the way enemies work, resulting in massive loads of enemies.
> 
> Heres the "fix": Don't use more than 4x speed, it shouldn't happen. For instance, the 256x speed or whatever, causes your base to become near-invincible.

This works, although I didn't use them in the save, I just had to delete it, and they don't seem to act weirdly again, although I did do something else too because I didn't want to spend another hour pushing through 4 cores, but for now, it seems to have done the trick, thanks.

**Comment by Anuken** [comment] 2022-11-06 18:39
I found the issue, it has nothing to do with timewarp. Missile units are incorrectly calculate as having near-zero DPS, so the squads for them get massive. This is now fixed.

**Comment by TheAirBlow** [comment] 2022-11-06 19:11
> Welp, then the message is for the OP, you get a free pass.

He's actually the person I playing with :trollface:

**Comment by TheAirBlow** [comment] 2022-11-06 19:14
> > ### Describe what you would like changed, and why.
> > I destroyed all cores except one, and after that I heard wave sounds... I placed a Scathe and saw this; ![image](https://user-images.githubusercontent.com/68467762/200131989-a046d534-1945-4ff1-b5c6-2d0f10a912f8.png) What the actual fuck is this? How am I even supposed to defend against that? Maybe they started to just multiply and camp this place because their place is lit. But still, getting like ~8 of them per wave is just something TOO hard to defend against.
> > Scathe attack attempt
> > Core death and defences die
> > Another core death and range of these fuckers
> > ### Describe the changes you want to propose. Include possible alternatives.
> > Remove the waves completely or make them less OP
> 
> You didn't.

I didn't do what?

**Comment by TheAirBlow** [comment] 2022-11-06 19:22
> Welp, then the message is for the OP, you get a free pass.

So you have the ability to read the damn username? The person who told you about mods **is not me**, but you then directed the response to me. Do you even know what is context?

**Closed** 2022-11-06 19:29 UTC
Labels: balancing/feedback
