### ISSUE TITLE
"Launch With All" option for launching to new zones

### ISSUE THREAD

**Issue by h3rlihy** [Anuken/Mindustry-Suggestions#1484] opened 2020-12-07 18:22 UTC
When launching to a new sector having a 'select all' or 'max' option if you are launching with a smaller core than currently using would be really helpful

**Comment by joshuaptfan** [comment] 2020-12-07 18:28
1. Please use the included template for feature requests, don't delete it then type your thing.
2. Duplicate of #1383.

**Closed** 2020-12-07 18:31 UTC
Labels: feature request
